// Generated by CoffeeScript 1.3.3
(function() {
  var Englishy, fn;

  fn = require('functools');

  Englishy = (function() {

    function Englishy(str) {
      this.string = str;
      this.lines = this.parse();
    }

    Englishy.prototype.parse = function() {
      var add_nulls, no_emptys, raw_lines, strip_empty;
      strip_empty = function(line) {
        return line.length > 1;
      };
      add_nulls = function(line) {
        return [line, null];
      };
      raw_lines = this.string.split("\n");
      no_emptys = fn.filter(strip_empty, raw_lines);
      return fn.map(add_nulls, no_emptys);
    };

    return Englishy;

  })();

  exports.Englishy = Englishy;

}).call(this);
